# Theme
# include themes/Catppuccin-Mocha.conf
include kanagawa.conf

# Font
font_family Maple Mono NF CN
font_size 11

# Cursor
cursor_shape block

# Keybindings
# ctrl+c: copy if selection, otherwise pass through to terminal (SIGINT)
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
